name: lint

on:
  push:
    branches: [main]

jobs:
  awesome-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run awesome-lint
        run: npx --yes awesome-lint@latest README.md
